"""Single source of truth for findings (friction log) and recommendations (improvement matrix).
build_report.py renders these into friction-log.csv and UX_AUDIT_REPORT.md."""

# Nielsen heuristics (short codes used in the log)
H = {
    'H1': 'H1 Visibility of system status', 'H2': 'H2 Match between system and real world', 'H3': 'H3 User control and freedom',
    'H4': 'H4 Consistency and standards', 'H5': 'H5 Error prevention', 'H6': 'H6 Recognition rather than recall',
    'H7': 'H7 Flexibility and efficiency of use', 'H8': 'H8 Aesthetic and minimalist design',
    'H9': 'H9 Help users recognize, diagnose, recover from errors', 'H10': 'H10 Help and documentation',
}

# id, journey, step, url, viewport, theme, heuristic, severity(0-4), observed_or_inferred, description, [screenshots], rec_id
F = [
 # ── J1 Home
 ('F01','J1',1,'/','desktop','dark+light','H8',3,'observed','At 1440×900 the first viewport holds only the eyebrow and the H1 ("IA pessoal e empresarial. Sob seu controle."); the lead is cut mid-sentence and no CTA is visible (0 CTAs in viewport, measured). The first action a desktop visitor can take is in the 12-item header.',['J1-01-hero-desktop-dark.png','J1-01-hero-desktop-light.png'],'R03'),
 ('F02','J1',1,'/','both','dark','H2',2,'inferred','The hero speaks to two audiences in one sentence ("Para você: chat privado sem censura… Para a sua empresa: …"). P1 (mobile, social) has to parse B2B infrastructure language; P2 (law-firm partner / hospital IT) meets "sem censura" in the first read, a mixed signal for a compliance buyer.',['J1-01-hero-mobile-dark.png','J1-01-hero-desktop-dark.png'],'R04'),
 ('F03','J1',3,'/','desktop','dark+light','H8',2,'observed','Desktop header = 12 text links + theme toggle (13 targets). "VoiceAI POWERED BY XSPACE" mixes product and vendor branding inside the nav. Plataforma / Segurança / Implantação are in-page anchors of the home, so from any other page they reload the home.',['J1-03-nav-desktop-dark.png','J1-03-nav-desktop-light.png'],'R05'),
 ('F04','J1',2,'/','both','dark+light','H4',2,'observed','The second banner ("IA Privada e sem censura*. Seats individuais disponíveis.") sends traffic to espera.html and planos.html#pessoal — not to /seats.html. The link inventory found zero inbound links to /seats.html anywhere on the site (only the sitemap lists it), although /seats.html is the clearest B2C landing (H1 + CTA above the fold).',['J1-02-second-banner-desktop-dark.png','J1-02-second-banner-mobile-dark.png','J3-09-seats-desktop-dark.png'],'R06'),
 ('F05','J1',2,'/','both','dark+light','H1',3,'observed','Waitlist counter credibility — needs verification. assets/contador.js computes the number from the clock: 1.317 + 132 × (hours since 08/09 15:00 BRT ÷ 2). Every visitor sees the same value, and it jumped from 23.493 to 23.625 at exactly 20:00 UTC during this audit. The number is not substantiated by any visible source and reads as social proof.',['J1-02-second-banner-desktop-dark.png','J4-01-espera-mobile-dark.png','J3-09-seats-desktop-dark.png'],'R02'),
 ('F06','J1',4,'/','both','dark','H4',3,'observed','Three parallel entry concepts compete from the first screen: "Criar conta grátis" (cadastro, account now, chat on 1/10), "Entrar na lista de espera" (no account), and "Pré-assinar" (Stripe, access 23/09). The CTA inventory shows 4 labels → cadastro, 3 → espera, 6 → Stripe and 9 → contact. The visitor must learn the difference between conta, lista and pré-assinatura before acting.',['J1-01-hero-mobile-dark.png','J1-04-two-paths-desktop-dark.png','J4-01-espera-desktop-dark.png'],'R01'),
 ('F07','J1',1,'/','both','dark','H8',1,'observed','The home is 19,637 px tall on mobile (~23 screens) and 15,007 px on desktop. B2C, B2B platform, mentoring, principles, capabilities, security and implementation all live on one page.',['J1-01-hero-full-mobile-dark.png','J1-01-hero-full-desktop-dark.png'],'R07'),
 ('F08','J1',5,'/','both','dark','H4',1,'observed','The footer tagline on every page says "Infraestrutura privada de inteligência artificial para empresas", contradicting the dual B2C/B2B positioning of the hero.',['J5-05-footer-desktop-dark.png'],'R04'),
 ('F09','J1',1,'/','both','light','—',0,'observed','Positive: the light theme toggle works (aria-pressed and aria-label switch, choice persisted in localStorage "trustio-theme"); measured text contrast in light theme passes AA (5.2–13.5:1).',['J1-01-hero-desktop-light.png','J1-01-hero-mobile-light.png'],'—'),
 # ── J2 VoiceAI
 ('F10','J2',5,'https://voice.trustio.com.br/credito-jus','both','dark','H9',4,'observed','"Chamada real ↗" (2 CTAs on /voice.html) points to voice.trustio.com.br/credito-jus, which has no DNS record (public DNS: NOERROR with no A/CNAME; auditor\'s Mac: NXDOMAIN). The most qualified B2B action on the page ends in a browser error.',['J2-05-handoff-dns-evidence-desktop-dark.png','J2-05-handoff-dns-evidence-mobile-dark.png'],'R08'),
 ('F11','J2',1,'/voice.html','desktop','dark','H8',2,'observed','On desktop the first viewport has no CTA (0 measured); the orb is the only interaction. On mobile "Criar um agente assim ↗" is visible, so the desktop layout under-serves the P2 persona who browses on a laptop.',['J2-01-voice-hero-desktop-dark.png','J2-01-voice-hero-mobile-dark.png'],'R03'),
 ('F12','J2',1,'/voice.html','both','dark','H2',2,'observed','"powered by xSpace · em produção" is unexplained. The body copy says the models are xAI\'s Grok Voice; a visitor cannot tell what xSpace is or whether a partnership exists (needs verification). "Em produção" is also unqualified (which customers, since when).',['J2-01-voice-hero-desktop-dark.png'],'R09'),
 ('F13','J2',3,'/voice.html','desktop','dark','—',0,'observed','Positive: one click on the orb gives immediate feedback — state "A BRUNA FALANDO…", live word-by-word caption, aria-pressed=true, progress ring. The clip is pre-recorded and ends on its own.',['J2-03-orb-first-response-desktop-dark.png','J2-02-orb-idle-desktop-dark.png'],'—'),
 ('F14','J2',6,'/console/','both','dark','H2',3,'observed','"Construir meu agente" / "Criar um agente assim" / "Testar no Agent Builder" open /console/, which shows production-looking data (1.284 chamadas · 24 h, 92 % resolvidas sem humano, "Produção" selected, "EM PRODUÇÃO" badges). The only disclosure is a small footnote "Métricas ilustrativas deste ambiente de demonstração". Needs verification of framing.',['J2-06-console-handoff-desktop-dark.png','J2-06-console-handoff-mobile-dark.png'],'R10'),
 ('F15','J2',4,'/voice.html','both','dark','H4',1,'observed','Channel cards nest a <button> inside role="listitem" articles (axe aria-allowed-role, 8 nodes). The same card both reveals an insight on hover and plays audio on click, with no visual difference between the two affordances (inferred).',['J2-04-channel-cards-desktop-dark.png','J2-04-channel-cards-mobile-dark.png'],'R16'),
 # ── J3 Plans
 ('F16','J3',1,'/planos.html','both','dark+light','H2',2,'observed','/planos opens on "Para empresas" with the H1 "Infraestrutura privada de IA. Contratada em minutos." A P1 visitor must find the "Para você" tab. The #pessoal deep link does select the B2C tab (verified), but only home links use it; the nav item "Planos" and the other pages open the B2B tab.',['J3-01-planos-mobile-dark.png','J3-01-planos-desktop-dark.png','J3-01-planos-desktop-light.png'],'R11'),
 ('F17','J3',8,'buy.stripe.com (7 links)','both','dark','H4',4,'observed','Stripe checkout does not look like Trustio. The Diagnóstico page is titled "Pagar JUICYSCORE", every checkout says "Pague com segurança em JUICYSCORE", and the B2C subscription mandate reads "Ao se inscrever, você autoriza a JUICYSCORE a cobrar de acordo com os termos até o cancelamento". The logo is a generic sparkle icon and the pay button is crimson (#DE3163). A buyer who clicked "Assinar" on Trustio sees another company\'s name at the moment of payment. The card statement descriptor probably shows the same name (inferred).',['J3-08-stripe-contratar-diagn-stico-desktop-dark.png','J3-05-stripe-assinar-starter-desktop-dark.png','J3-05-stripe-pr-assinar-entrar-em-23-09-full-mobile-dark.png'],'R12'),
 ('F18','J3',5,'buy.stripe.com (Starter, Pessoal)','both','dark','H4',3,'observed','Delivery promises differ between site and checkout. The /planos H1 says "Contratada em minutos", but the Starter checkout says "O ambiente é provisionado em até 5 dias úteis após a confirmação". The site says "Sem fila e sem aprovação manual: na data, sua conta abre sozinha", but the Pessoal checkout says "depois, o acesso é liberado em até 1 dia útil".',['J3-05-stripe-assinar-starter-desktop-dark.png','J3-05-stripe-pr-assinar-entrar-em-23-09-full-mobile-dark.png','J3-01-planos-desktop-dark.png'],'R11'),
 ('F19','J3',6,'buy.stripe.com (B2B)','desktop','dark','H2',2,'observed','From the audit network (not in Brazil) the B2B checkouts defaulted to USD (US$ 590,98 / 1.609,92 / 4.055,38) with "As cobranças vão variar de acordo com as taxas de câmbio" and billing country "Estados Unidos". /planos promises "Pague em reais… sem IOF, sem surpresa de dólar". This is likely Stripe geolocation; needs verification from a Brazilian IP.',['J3-06-stripe-assinar-pro-desktop-dark.png','J3-07-stripe-assinar-dedicado-desktop-dark.png'],'R12'),
 ('F20','J3',5,'buy.stripe.com (7 links)','both','dark','H4',3,'inferred','All 7 checkout captures offered only "Cartão". The site promises Pix, Apple Pay and Google Pay ("PIX ACEITO" chip, method chips on /planos). Wallets cannot render in headless Chromium, and Pix requires BRL and Brazil, so this needs verification on a real Brazilian phone before 23/09.',['J3-05-stripe-pr-assinar-entrar-em-23-09-mobile-dark.png','J3-06-stripe-comprar-passe-mobile-dark.png','J3-02-para-voce-mobile-dark.png'],'R12'),
 ('F21','J3',2,'/planos.html#pessoal','both','dark+light','H8',1,'observed','B2C price anchoring is clear: monthly R$ 79 "Recomendado", 7-day pass R$ 24,90, annual R$ 790 "Dois meses grátis" (≈ R$ 65,80/mês). But every paid card also carries "Ou entrar na lista grátis ↓", which puts the free path inside each paid card the day before the 23/09 pre-sale.',['J3-02-para-voce-desktop-dark.png','J3-02-para-voce-mobile-dark.png'],'R01'),
 ('F22','J3',4,'/planos.html','mobile','dark+light','H7',2,'observed','On mobile the B2B comparison table (640 px) sits in a 358 px scroll wrapper with no scroll cue, and the wrapper is not keyboard-focusable (axe scrollable-region-focusable, serious). The same pattern appears on /modelos (778 px table).',['J3-04-compare-table-mobile-dark.png','J6-06-overflow-planos-table-mobile-dark.png','J6-06-overflow-modelos-table-mobile-dark.png'],'R16'),
 ('F23','J3',3,'/planos.html#pessoal','both','dark+light','H1',0,'observed','Positive: the "Estado de hoje: cadastro aberto, chat ainda fechado…" block states both dates unambiguously. It is repeated almost verbatim on 5 pages, which is consistent but adds length.',['J3-03-early-access-desktop-dark.png','J3-03-early-access-mobile-light.png'],'—'),
 ('F24','J3',9,'/seats.html','both','dark','H4',3,'observed','On /seats.html the header anchors (#plataforma, #seguranca, #implantacao, #contato) point to IDs that do not exist on that page, so 4 nav items do nothing there. This was found by the link check (anchor MISSING).',['J3-09-seats-desktop-dark.png','J3-09-seats-mobile-dark.png'],'R06'),
 # ── J4 Waitlist & demo
 ('F25','J4',3,'/espera.html','both','dark','H4',2,'observed','Contradictory microcopy: the label reads "NOME obrigatório", while the helper under the phone field says "Só o e-mail é obrigatório". The name field is required in the markup.',['J4-03-invalid-email-mobile-dark.png','J4-03-invalid-email-desktop-dark.png'],'R13'),
 ('F26','J4',2,'/espera.html','both','dark','H9',2,'observed','Validation relies on native browser bubbles, whose language follows the browser, not the page. An invalid e-mail ("teste@") only turns the border pink (#FF7AA8), with no text, no aria-invalid and no aria-describedby. The phone field accepts "11" (no mask or pattern).',['J4-02-empty-validation-desktop-dark.png','J4-03-invalid-email-desktop-dark.png','J4-03-invalid-email-mobile-dark.png'],'R13'),
 ('F27','J4',1,'/espera.html','mobile','dark','H8',2,'observed','On mobile the first field appears about 2 screens below the fold, after the status box, 4 stat tiles and a 4-step explainer. The first viewport contains no field and no button.',['J4-01-espera-mobile-dark.png','J4-01-espera-full-mobile-dark.png'],'R13'),
 ('F28','J4',6,'/espera.html','both','dark','H4',3,'observed','In the waitlist form, "Pré-assinar" means "enviamos o link de pagamento" (by e-mail, later), while /planos has instant Stripe links. Two pre-sale paths with different latency exist the day before the 23/09 early-access date. The submit label "Quero pré-assinar e entrar em 23/09 ↗" implies immediate payment. Stopped by guardrail before submit.',['J4-06-prefilled-stop-before-submit-desktop-dark.png','J4-06-prefilled-stop-before-submit-mobile-dark.png'],'R01'),
 ('F29','J4',7,'/planos.html#espera-form','both','dark','H4',2,'observed','/planos embeds a different waitlist form (email, whatsapp, plano, acesso, uso) from /espera (nome, email, telefone, tipo, segmento, empresa, tamanho, acesso, observacao), with the same id="espera-form". The same promise yields different lead data depending on the page.',['J4-07-planos-embedded-waitlist-desktop-dark.png','J4-07-planos-embedded-waitlist-mobile-dark.png'],'R13'),
 ('F30','J4',5,'/espera.html','both','dark','—',0,'observed','Positive: choosing "Para minha empresa" reveals Segmento (required, 8 verticals incl. Jurídico and Saúde), Empresa and Tamanho, and hides the B2C plan radios. The B2C/B2B segmentation is clear.',['J4-05-b2b-segment-desktop-dark.png','J4-05-b2b-segment-mobile-dark.png'],'—'),
 ('F31','J4',8,'/#contato','both','dark','H7',3,'observed','Every B2B "demo" trigger (9 labels: "Falar com um arquiteto", "Planejar a implantação…", "Ativar este canal"…) resolves to a mailto: link. The section says "Sem formulários". There is no scheduler and no security pack. mailto: does nothing on machines without a mail client; the "Copiar" button mitigates this (impact inferred).',['J4-08-contato-demo-desktop-dark.png','J4-08-contato-demo-mobile-dark.png'],'R14'),
 ('F32','J4',9,'/cadastro.html','both','dark','H2',2,'observed','The home primary CTA "Criar conta grátis" opens a password sign-up (account now, chat on 1/10). This adds a third concept ("conta") next to lista and pré-assinatura. Observed only; no account was created.',['J4-09-cadastro-mobile-dark.png','J4-09-cadastro-desktop-dark.png'],'R01'),
 # ── J5 Trust & legal
 ('F33','J5',5,'all pages (footer)','both','dark','H4',3,'observed','Needs verification: the footer of every page claims "Certificação ISO 27001" with an ISO seal, but gives no certificate number, issuer, scope or verification link. The seal is not linked.',['J5-05-footer-desktop-dark.png','J5-05-footer-mobile-dark.png'],'R15'),
 ('F34','J5',5,'all pages (footer)','both','dark','H4',3,'observed','Needs verification: the ANPD logo is shown among the seals. ANPD is the data-protection regulator and does not certify companies, so the logo can read as an endorsement. Legal review recommended.',['J5-05-footer-desktop-dark.png'],'R15'),
 ('F35','J5',3,'/fundador.html','both','dark','H2',2,'observed','Needs verification: /fundador lists "ISO 27001, SOC 2 Type II e ISO 9001" under "Credenciais que sustentam a confiança". It is ambiguous whether these are personal qualifications or company certifications.',['J5-03-fundador-full-desktop-dark.png','J5-03-fundador-desktop-dark.png'],'R15'),
 ('F36','J5',6,'/privacidade.html','both','dark','H4',4,'observed','Data-residency claims contradict the privacy policy. Marketing says "tudo roda no Brasil" (/planos B2C), "inferência e dados hospedados no Brasil" (/seats) and "Inferência, gravações e registros permanecem em infraestrutura nacional" (home #seguranca). The privacy policy says B2C prompts go to a contracted LLM provider whose country is disclosed only on request and "se o provedor processar fora do Brasil, isso caracteriza transferência internacional". This affects the "Dados no Brasil" pillar directly.',['J5-06-privacidade-full-desktop-dark.png','J3-03-early-access-desktop-dark.png','J5-04-seguranca-desktop-dark.png'],'R17'),
 ('F37','J5',5,'all pages','both','dark','H10',3,'observed','A text search of the footer, /planos and /privacidade found no legal entity identity (razão social, CNPJ, address) and no named Encarregado (DPO). A paid offer is live. Legal verification recommended (e-commerce disclosure and LGPD Encarregado disclosure).',['J5-05-footer-desktop-dark.png','J5-06-privacidade-full-desktop-dark.png'],'R18'),
 ('F38','J5',4,'/#seguranca','desktop','dark','H10',2,'inferred','For P2, the security section is prose plus principles. It offers no downloadable security pack (architecture diagram, subprocessors, DPA, retention, pen-test summary) and no verifiable artefacts, so a hospital IT lead cannot complete a vendor assessment from the site.',['J5-04-seguranca-desktop-dark.png','J5-04-seguranca-mobile-dark.png'],'R14'),
 ('F39','J5',6,'/privacidade.html','both','dark','H2',1,'observed','The privacy policy is plain-language and candid (e.g. "Administradores da Trustio conseguem acessar conversas para suporte e para investigar abuso"). Marketing pages present "Privada" without this nuance.',['J5-06-privacidade-desktop-dark.png'],'R17'),
 # ── J6 Mobile navigation (+ desktop keyboard)
 ('F40','J6',2,'/','mobile','dark','H8',2,'observed','The mobile menu has 11 items × 78 px = 885 px inside an 844 px viewport, so "Entrar" falls below the menu fold. Focus stays on the toggle when the menu opens (focus not moved into the dialog).',['J6-02-menu-open-mobile-dark.png','J1-03-nav-open-mobile-dark.png'],'R05'),
 ('F41','J6',3,'/','mobile','dark','—',0,'observed','Positive: Escape closes the menu and focus returns to the toggle. Body scroll is locked while the menu is open. Tapping "Segurança" closes the menu and lands on the section below the 73 px sticky header.',['J6-03-menu-escape-mobile-dark.png','J6-04-menu-anchor-seguranca-mobile-dark.png'],'—'),
 ('F42','J6',5,'/','mobile','dark','H7',1,'observed','12 footer links are 23 px tall on mobile: below the 24 px minimum of WCAG 2.2 SC 2.5.8 unless the spacing exception applies, and well below the 44 px iOS guidance. All header targets are ≥ 44 px.',['J6-05-tap-targets-annotated-mobile-dark.png','J6-05-tap-targets-annotated-full-mobile-dark.png'],'R16'),
 ('F43','J6',1,'/','desktop','dark','—',0,'observed','Positive: the first Tab reveals the "Ir para o conteúdo" skip link. Every stop in the header/hero shows a 2 px solid #5EA7FF focus ring, and the order is logical.',['J6-01-keyboard-skip-link-desktop-dark.png','J6-02-keyboard-focus-ring-desktop-dark.png'],'—'),
 # ── Cross-cutting technical
 ('F44','J1',1,'/ (all pages)','both','dark','H1',3,'observed','The CSP (script-src/connect-src + CORS) blocks the Cloudflare Web Analytics beacon on every page, and on / it also refuses inline styles (20 console errors per load). Funnel analytics are therefore likely not collected before launch, and some intended inline styling is not applied.',['J1-01-hero-desktop-dark.png'],'R19'),
 ('F45','J2',1,'/voice.html, /planos.html','both','dark','H4',1,'observed','/voice-base.css?v=a87701eb returns 404 on /voice.html and /planos.html (requested from the site root instead of /assets/, which returns 200). The cause needs a developer check.',['J2-01-voice-hero-desktop-dark.png'],'R19'),
 ('F46','J2',1,'/voice.html','mobile','dark','H1',2,'observed','Lighthouse mobile (lab) gives /voice.html Performance 38 (LCP 6.6 s) and the home 73 (TBT 690 ms); content pages score 91–92. Lab WebGL runs on software rendering, which inflates TBT, so the numbers are directional only.',['J2-01-voice-hero-mobile-dark.png','J1-01-hero-mobile-dark.png'],'R20'),
 ('F47','J4',3,'/espera.html','mobile','dark','H8',1,'observed','Form labels and kickers are 10.5–11 px mono uppercase with wide tracking (e.g. "NOME obrigatório" at 10.5 px). Contrast passes (6.9–11:1 measured), but the size is small for a mobile form.',['J4-03-invalid-email-mobile-dark.png'],'R16'),
]

# id, recommendation, evidence, impact(1-5), effort(S/M/L), confidence, category, KPI, deadline
R = [
 ('R01','One pre-launch conversion model. Until 23/09 the primary CTA everywhere is "Pré-assinar e entrar em 23/09" (Stripe), with "Lista grátis · acesso em 1º/10" as the only secondary. Make the waitlist\'s "Pré-assinar" option redirect straight to Stripe instead of "enviamos o link". Remove "Ou entrar na lista grátis" from inside paid cards. Show "Criar conta" only after checkout or after 1º/10.','F06, F21, F28, F32',5,'M','High','Strategic','Visitor → pre-subscription rate; waitlist → paid rate','2026-09-23'),
 ('R02','Replace the clock-driven counter with the real count from the signup API (cached, e.g. hourly), or remove the number and keep only the countdown. Never show a figure that cannot be substantiated.','F05',4,'S','High','Quick Win','Trust-related bounce; legal sign-off','2026-09-23'),
 ('R03','Put the primary CTA in the first viewport on desktop. Cap the hero H1 so eyebrow + H1 + lead + CTA fit in 1440×900 (e.g. font-size: clamp(3rem, 6.2vw, 6rem)). Apply the same to /voice.html.','F01, F11',4,'S','High','Quick Win','Hero CTA CTR; % of sessions clicking before first scroll','2026-09-23'),
 ('R04','One-sentence value proposition per persona, plus a footer tagline that covers both audiences (PT-BR rewrites in §8.5).','F02, F08',4,'S','Medium','Quick Win','5-second-test recall; bounce rate on /','2026-10-01'),
 ('R05','Navigation IA: at most 7 top-level items (Chat privado · VoiceAI · Jurídico · Modelos · Segurança · Planos), with Manifesto and Fundador moved to the footer, plus "Entrar" and one primary CTA. The mobile menu fits one screen with the CTA pinned, and focus moves into the menu on open.','F03, F40',3,'M','Medium','Strategic','Nav CTR; menu-open → click rate','2026-10-01'),
 ('R06','Make /seats.html the B2C landing. Link it from the home banner, the nav ("Para você") and social ads, and fix its header anchors to index.html#… (they currently point at IDs that do not exist).','F04, F24',4,'S','High','Quick Win','Social landing CVR; broken-anchor clicks = 0','2026-09-23'),
 ('R07','Split the 23-screen home: a lean home (hero + two persona doors + proof + CTA) and a dedicated /empresas page for platform, mentoring and implementation.','F07',3,'L','Medium','Strategic','Scroll depth; conversion per persona','Post-launch'),
 ('R08','Restore the VoiceAI "Chamada real" hand-off today. Publish the DNS record for voice.trustio.com.br, or point the CTA to an on-site demo or a callable number, and add an uptime check on the URL.','F10',5,'S','High','Quick Win','Demo starts; dead-link clicks = 0','2026-09-23'),
 ('R09','Explain "xSpace" in one line or drop it from the nav label ("VoiceAI"). Keep vendor attribution factual ("modelos Grok Voice da xAI via API oficial") and qualify "em produção" with who and since when.','F12',2,'S','Medium','Quick Win','VoiceAI nav CTR; support questions about xSpace','2026-10-01'),
 ('R10','Label the console as a demo: a persistent banner "Demonstração · dados fictícios", default the environment toggle to "Sandbox", and replace "EM PRODUÇÃO" badges in demo data with neutral states.','F14',3,'S','High','Quick Win','Demo → contact rate; complaints','2026-10-01'),
 ('R11','Align /planos with reality and with the persona. Change the H1 "Contratada em minutos" to match the 5-business-day provisioning (or fix provisioning), open on "Para você" when the visitor arrives from B2C sources (#pessoal, utm, referrer), and keep delivery times identical on /planos and in Stripe.','F16, F18',3,'S','High','Quick Win','/planos → checkout CTR','2026-09-23'),
 ('R12','Stripe account settings before 23/09: public business name "Trustio", statement descriptor "TRUSTIO", Trustio icon/logo, brand colour #2563EB, BRL presentment for Brazilian products, Pix + Apple Pay + Google Pay enabled. Test from a Brazilian phone and IP.','F17, F19, F20',5,'S','High','Quick Win','Checkout completion; chargeback / "unknown merchant" disputes','2026-09-23'),
 ('R13','Waitlist form. Fix the "Nome obrigatório" vs "Só o e-mail é obrigatório" contradiction. Add inline PT-BR errors with aria-invalid and aria-describedby, and a Brazilian phone mask. Bring the form into the first mobile viewport (stats after the form). Use one field schema for /espera and the /planos embed.','F25, F26, F27, F29',3,'S','High','Quick Win','Form start → submit rate; validation-error rate','2026-09-23'),
 ('R14','B2B path: an "Agendar conversa (30 min)" scheduler, plus a downloadable "Pacote de segurança" (architecture, subprocessors, DPA template, retention, pen-test summary) gated only by e-mail.','F31, F38',4,'M','Medium','Strategic','B2B demo bookings; time-to-first-meeting','2026-10-01'),
 ('R15','Trust seals: show the ISO 27001 certificate number, certification body, scope and a verification link, or remove the seal until it can be verified. Remove the ANPD logo and replace it with text plus the Encarregado contact. Separate founder credentials from company certifications.','F33, F34, F35',4,'S','High','Quick Win','Legal/compliance sign-off; security-questionnaire friction','2026-09-23'),
 ('R16','Accessibility and mobile polish: make table scroll regions focusable (tabindex="0" + aria-label) and add a scroll cue; make channel cards a single button per card; give footer links ≥ 24 px (ideally 44 px) height; set a 12 px minimum for labels.','F15, F22, F42, F47',2,'S','High','Quick Win','axe violations = 0; tap-target audit','2026-10-01'),
 ('R17','Truth in advertising for "Dados no Brasil". Either run B2C inference in Brazil before claiming it, or qualify the copy ("dados armazenados no Brasil; inferência do plano individual por provedor contratado — país informado em /privacidade"). Publish the provider and country on the privacy page, and mention admin access where "Privada" is promised.','F36, F39',5,'M','High','Strategic','Legal sign-off; complaint / Procon exposure','2026-09-23'),
 ('R18','Legal identity: add razão social, CNPJ, address and Encarregado (name + e-mail) to the footer, /privacidade and the Stripe receipt/footer.','F37',4,'S','High','Quick Win','Legal checklist complete','2026-09-23'),
 ('R19','Instrumentation and hygiene: allow the analytics endpoint in CSP (or self-host analytics), move inline styles into CSS, fix the voice-base.css path, and ship funnel events (hero_cta_click, waitlist_start, waitlist_submit, checkout_open, checkout_complete).','F44, F45',4,'S','High','Quick Win','Events received per step; funnel dashboard live','2026-09-23'),
 ('R20','Performance: lazy-init WebGL orbs and the network canvas on interaction or in view, pause offscreen, respect prefers-reduced-motion and Save-Data, and cap canvas DPR at 1.5. Targets: LCP < 2.5 s, INP < 200 ms at p75.','F46',3,'M','Medium','Strategic','CrUX p75 LCP/INP on / and /voice.html','Post-launch'),
 ('R21','SOTA Trust Center (/seguranca): verifiable certifications, live status, subprocessors with country, per-product data-flow diagrams (B2C vs B2B), and a changelog of security commitments.','F33, F36, F38',4,'L','Medium','SOTA','B2B sales-cycle length; security-review pass rate','Post-launch'),
 ('R22','SOTA persona switch: a segmented control "Para mim / Para minha empresa" in the hero that swaps copy, CTA and proof, persisted per visitor, with the motion spec in §8.3.','F02, F06',3,'M','Medium','SOTA','CTR by segment; time-to-first-CTA','Post-launch'),
 ('R23','SOTA checkout: Stripe Embedded Checkout / Payment Element on trustio.com.br with Trustio branding, inline Pix QR code with expiry timer, and a confirmation screen that states the access date.','F17, F20',4,'L','Medium','SOTA','Checkout completion; Pix share of payments','Post-launch'),
]
